<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cities')->insert([
            ["state_id"=>1,"code"=>1,"name"=>"MEDELLIN"],
            ["state_id"=>1,"code"=>2,"name"=>"ABEJORRAL"],
            ["state_id"=>1,"code"=>4,"name"=>"ABRIAQUI"],
            ["state_id"=>1,"code"=>21,"name"=>"ALEJANDRIA"],
            ["state_id"=>1,"code"=>30,"name"=>"AMAGA"],
            ["state_id"=>1,"code"=>31,"name"=>"AMALFI"],
            ["state_id"=>1,"code"=>34,"name"=>"ANDES"],
            ["state_id"=>1,"code"=>36,"name"=>"ANGELOPOLIS"],
            ["state_id"=>1,"code"=>38,"name"=>"ANGOSTURA"],
            ["state_id"=>1,"code"=>40,"name"=>"ANORI"],
            ["state_id"=>1,"code"=>42,"name"=>"ANTIOQUIA"],
            ["state_id"=>1,"code"=>44,"name"=>"ANZA"],
            ["state_id"=>1,"code"=>45,"name"=>"APARTADO"],
            ["state_id"=>1,"code"=>51,"name"=>"ARBOLETES"],
            ["state_id"=>1,"code"=>55,"name"=>"ARGELIA"],
            ["state_id"=>1,"code"=>59,"name"=>"ARMENIA"],
            ["state_id"=>1,"code"=>79,"name"=>"BARBOSA"],
            ["state_id"=>1,"code"=>86,"name"=>"BELMIRA"],
            ["state_id"=>1,"code"=>88,"name"=>"BELLO"],
            ["state_id"=>1,"code"=>91,"name"=>"BETANIA"],
            ["state_id"=>1,"code"=>93,"name"=>"BETULIA"],
            ["state_id"=>1,"code"=>101,"name"=>"BOLIVAR"],
            ["state_id"=>1,"code"=>107,"name"=>"BRICEÑO"],
            ["state_id"=>1,"code"=>113,"name"=>"BURITICA"],
            ["state_id"=>1,"code"=>120,"name"=>"CACERES"],
            ["state_id"=>1,"code"=>125,"name"=>"CAICEDO"],
            ["state_id"=>1,"code"=>129,"name"=>"CALDAS"],
            ["state_id"=>1,"code"=>134,"name"=>"CAMPAMENTO"],
            ["state_id"=>1,"code"=>138,"name"=>"CAÑASGORDAS"],
            ["state_id"=>1,"code"=>142,"name"=>"CARACOLI"],
            ["state_id"=>1,"code"=>145,"name"=>"CARAMANTA"],
            ["state_id"=>1,"code"=>147,"name"=>"CAREPA"],
            ["state_id"=>1,"code"=>148,"name"=>"CARMEN DE VIBORAL"],
            ["state_id"=>1,"code"=>150,"name"=>"CAROLINA"],
            ["state_id"=>1,"code"=>154,"name"=>"CAUCASIA"],
            ["state_id"=>1,"code"=>172,"name"=>"CHIGORODO"],
            ["state_id"=>1,"code"=>190,"name"=>"CISNEROS"],
            ["state_id"=>1,"code"=>197,"name"=>"COCORNA"],
            ["state_id"=>1,"code"=>206,"name"=>"CONCEPCION"],
            ["state_id"=>1,"code"=>209,"name"=>"CONCORDIA"],
            ["state_id"=>1,"code"=>212,"name"=>"COPACABANA"],
            ["state_id"=>1,"code"=>234,"name"=>"DABEIBA"],
            ["state_id"=>1,"code"=>237,"name"=>"DON MATIAS"],
            ["state_id"=>1,"code"=>240,"name"=>"EBEJICO"],
            ["state_id"=>1,"code"=>250,"name"=>"EL BAGRE"],
            ["state_id"=>1,"code"=>264,"name"=>"ENTRERRIOS"],
            ["state_id"=>1,"code"=>266,"name"=>"ENVIGADO"],
            ["state_id"=>1,"code"=>282,"name"=>"FREDONIA"],
            ["state_id"=>1,"code"=>284,"name"=>"FRONTINO"],
            ["state_id"=>1,"code"=>306,"name"=>"GIRALDO"],
            ["state_id"=>1,"code"=>308,"name"=>"GIRARDOTA"],
            ["state_id"=>1,"code"=>310,"name"=>"GOMEZ PLATA"],
            ["state_id"=>1,"code"=>313,"name"=>"GRANADA"],
            ["state_id"=>1,"code"=>315,"name"=>"GUADALUPE"],
            ["state_id"=>1,"code"=>318,"name"=>"GUARNE"],
            ["state_id"=>1,"code"=>321,"name"=>"GUATAPE"],
            ["state_id"=>1,"code"=>347,"name"=>"HELICONIA"],
            ["state_id"=>1,"code"=>353,"name"=>"HISPANIA"],
            ["state_id"=>1,"code"=>360,"name"=>"ITAGUI"],
            ["state_id"=>1,"code"=>361,"name"=>"ITUANGO"],
            ["state_id"=>1,"code"=>364,"name"=>"JARDIN"],
            ["state_id"=>1,"code"=>368,"name"=>"JERICO"],
            ["state_id"=>1,"code"=>376,"name"=>"LA CEJA"],
            ["state_id"=>1,"code"=>380,"name"=>"LA ESTRELLA"],
            ["state_id"=>1,"code"=>390,"name"=>"LA PINTADA"],
            ["state_id"=>1,"code"=>400,"name"=>"LA UNION"],
            ["state_id"=>1,"code"=>411,"name"=>"LIBORINA"],
            ["state_id"=>1,"code"=>425,"name"=>"MACEO"],
            ["state_id"=>1,"code"=>440,"name"=>"MARINILLA"],
            ["state_id"=>1,"code"=>467,"name"=>"MONTEBELLO"],
            ["state_id"=>1,"code"=>475,"name"=>"MURINDO"],
            ["state_id"=>1,"code"=>480,"name"=>"MUTATA"],
            ["state_id"=>1,"code"=>483,"name"=>"NARIÑO"],
            ["state_id"=>1,"code"=>490,"name"=>"NECOCLI"],
            ["state_id"=>1,"code"=>495,"name"=>"NECHI"],
            ["state_id"=>1,"code"=>501,"name"=>"OLAYA"],
            ["state_id"=>1,"code"=>541,"name"=>"PEÑOL"],
            ["state_id"=>1,"code"=>543,"name"=>"PEQUE"],
            ["state_id"=>1,"code"=>576,"name"=>"PUEBLORRICO"],
            ["state_id"=>1,"code"=>579,"name"=>"PUERTO BERRIO"],
            ["state_id"=>1,"code"=>585,"name"=>"PUERTO NARE (LA MAGDALENA)"],
            ["state_id"=>1,"code"=>591,"name"=>"PUERTO TRIUNFO"],
            ["state_id"=>1,"code"=>604,"name"=>"REMEDIOS"],
            ["state_id"=>1,"code"=>607,"name"=>"RETIRO"],
            ["state_id"=>1,"code"=>615,"name"=>"RIONEGRO"],
            ["state_id"=>1,"code"=>628,"name"=>"SABANALARGA"],
            ["state_id"=>1,"code"=>631,"name"=>"SABANETA"],
            ["state_id"=>1,"code"=>642,"name"=>"SALGAR"],
            ["state_id"=>1,"code"=>647,"name"=>"SAN ANDRES"],
            ["state_id"=>1,"code"=>649,"name"=>"SAN CARLOS"],
            ["state_id"=>1,"code"=>652,"name"=>"SAN FRANCISCO"],
            ["state_id"=>1,"code"=>656,"name"=>"SAN JERONIMO"],
            ["state_id"=>1,"code"=>658,"name"=>"SAN JOSE DE LA MONTAÑA"],
            ["state_id"=>1,"code"=>659,"name"=>"SAN JUAN DE URABA"],
            ["state_id"=>1,"code"=>660,"name"=>"SAN LUIS"],
            ["state_id"=>1,"code"=>664,"name"=>"SAN PEDRO"],
            ["state_id"=>1,"code"=>665,"name"=>"SAN PEDRO DE URABA"],
            ["state_id"=>1,"code"=>667,"name"=>"SAN RAFAEL"],
            ["state_id"=>1,"code"=>670,"name"=>"SAN ROQUE"],
            ["state_id"=>1,"code"=>674,"name"=>"SAN VICENTE"],
            ["state_id"=>1,"code"=>679,"name"=>"SANTA BARBARA"],
            ["state_id"=>1,"code"=>686,"name"=>"SANTA ROSA DE OSOS"],
            ["state_id"=>1,"code"=>690,"name"=>"SANTO DOMINGO"],
            ["state_id"=>1,"code"=>697,"name"=>"SANTUARIO"],
            ["state_id"=>1,"code"=>736,"name"=>"SEGOVIA"],
            ["state_id"=>1,"code"=>756,"name"=>"SONSON"],
            ["state_id"=>1,"code"=>761,"name"=>"SOPETRAN"],
            ["state_id"=>1,"code"=>789,"name"=>"TAMESIS"],
            ["state_id"=>1,"code"=>790,"name"=>"TARAZA"],
            ["state_id"=>1,"code"=>792,"name"=>"TARSO"],
            ["state_id"=>1,"code"=>809,"name"=>"TITIRIBI"],
            ["state_id"=>1,"code"=>819,"name"=>"TOLEDO"],
            ["state_id"=>1,"code"=>837,"name"=>"TURBO"],
            ["state_id"=>1,"code"=>842,"name"=>"URAMITA"],
            ["state_id"=>1,"code"=>847,"name"=>"URRAO"],
            ["state_id"=>1,"code"=>854,"name"=>"VALDIVIA"],
            ["state_id"=>1,"code"=>856,"name"=>"VALPARAISO"],
            ["state_id"=>1,"code"=>858,"name"=>"VEGACHI"],
            ["state_id"=>1,"code"=>861,"name"=>"VENECIA"],
            ["state_id"=>1,"code"=>873,"name"=>"VIGIA DEL FUERTE"],
            ["state_id"=>1,"code"=>885,"name"=>"YALI"],
            ["state_id"=>1,"code"=>887,"name"=>"YARUMAL"],
            ["state_id"=>1,"code"=>890,"name"=>"YOLOMBO"],
            ["state_id"=>1,"code"=>893,"name"=>"YONDO"],
            ["state_id"=>1,"code"=>895,"name"=>"ZARAGOZA"],
            ["state_id"=>2,"code"=>1,"name"=>"BARRANQUILLA"],
            ["state_id"=>2,"code"=>78,"name"=>"BARANOA"],
            ["state_id"=>2,"code"=>137,"name"=>"CAMPO DE LA CRUZ"],
            ["state_id"=>2,"code"=>141,"name"=>"CANDELARIA"],
            ["state_id"=>2,"code"=>296,"name"=>"GALAPA"],
            ["state_id"=>2,"code"=>372,"name"=>"JUAN DE ACOSTA"],
            ["state_id"=>2,"code"=>421,"name"=>"LURUACO"],
            ["state_id"=>2,"code"=>433,"name"=>"MALAMBO"],
            ["state_id"=>2,"code"=>436,"name"=>"MANATI"],
            ["state_id"=>2,"code"=>520,"name"=>"PALMAR DE VARELA"],
            ["state_id"=>2,"code"=>549,"name"=>"PIOJO"],
            ["state_id"=>2,"code"=>558,"name"=>"POLO NUEVO"],
            ["state_id"=>2,"code"=>560,"name"=>"PONEDERA"],
            ["state_id"=>2,"code"=>573,"name"=>"PUERTO COLOMBIA"],
            ["state_id"=>2,"code"=>606,"name"=>"REPELON"],
            ["state_id"=>2,"code"=>634,"name"=>"SABANAGRANDE"],
            ["state_id"=>2,"code"=>638,"name"=>"SABANALARGA"],
            ["state_id"=>2,"code"=>675,"name"=>"SANTA LUCIA"],
            ["state_id"=>2,"code"=>685,"name"=>"SANTO TOMAS"],
            ["state_id"=>2,"code"=>758,"name"=>"SOLEDAD"],
            ["state_id"=>2,"code"=>770,"name"=>"SUAN"],
            ["state_id"=>2,"code"=>832,"name"=>"TUBARA"],
            ["state_id"=>2,"code"=>849,"name"=>"USIACURI"],
            ["state_id"=>3,"code"=>1,"name"=>"Santa Fe de Bogotá"],
            ["state_id"=>3,"code"=>1,"name"=>"USAQUEN"],
            ["state_id"=>3,"code"=>2,"name"=>"CHAPINERO"],
            ["state_id"=>3,"code"=>3,"name"=>"SANTA FE"],
            ["state_id"=>3,"code"=>4,"name"=>"SAN CRISTOBAL"],
            ["state_id"=>3,"code"=>5,"name"=>"USME"],
            ["state_id"=>3,"code"=>6,"name"=>"TUNJUELITO"],
            ["state_id"=>3,"code"=>7,"name"=>"BOSA"],
            ["state_id"=>3,"code"=>8,"name"=>"KENNEDY"],
            ["state_id"=>3,"code"=>9,"name"=>"FONTIBON"],
            ["state_id"=>3,"code"=>10,"name"=>"ENGATIVA"],
            ["state_id"=>3,"code"=>11,"name"=>"SUBA"],
            ["state_id"=>3,"code"=>12,"name"=>"BARRIOS UNIDOS"],
            ["state_id"=>3,"code"=>13,"name"=>"TEUSAQUILLO"],
            ["state_id"=>3,"code"=>14,"name"=>"MARTIRES"],
            ["state_id"=>3,"code"=>15,"name"=>"ANTONIO NARIÑO"],
            ["state_id"=>3,"code"=>16,"name"=>"PUENTE ARANDA"],
            ["state_id"=>3,"code"=>17,"name"=>"CANDELARIA"],
            ["state_id"=>3,"code"=>18,"name"=>"RAFAEL URIBE"],
            ["state_id"=>3,"code"=>19,"name"=>"CIUDAD BOLIVAR"],
            ["state_id"=>3,"code"=>20,"name"=>"SUMAPAZ"],
            ["state_id"=>4,"code"=>1,"name"=>"CARTAGENA (DISTRITO TURISTICO Y CULTURAL DE CARTAGENA)"],
            ["state_id"=>4,"code"=>6,"name"=>"ACHI"],
            ["state_id"=>4,"code"=>30,"name"=>"ALTOS DEL ROSARIO"],
            ["state_id"=>4,"code"=>42,"name"=>"ARENAL"],
            ["state_id"=>4,"code"=>52,"name"=>"ARJONA"],
            ["state_id"=>4,"code"=>62,"name"=>"ARROYOHONDO"],
            ["state_id"=>4,"code"=>74,"name"=>"BARRANCO DE LOBA"],
            ["state_id"=>4,"code"=>140,"name"=>"CALAMAR"],
            ["state_id"=>4,"code"=>160,"name"=>"CANTAGALLO"],
            ["state_id"=>4,"code"=>188,"name"=>"CICUCO"],
            ["state_id"=>4,"code"=>212,"name"=>"CORDOBA"],
            ["state_id"=>4,"code"=>222,"name"=>"CLEMENCIA"],
            ["state_id"=>4,"code"=>244,"name"=>"EL CARMEN DE BOLIVAR"],
            ["state_id"=>4,"code"=>248,"name"=>"EL GUAMO"],
            ["state_id"=>4,"code"=>268,"name"=>"EL PEÑON"],
            ["state_id"=>4,"code"=>300,"name"=>"HATILLO DE LOBA"],
            ["state_id"=>4,"code"=>430,"name"=>"MAGANGUE"],
            ["state_id"=>4,"code"=>433,"name"=>"MAHATES"],
            ["state_id"=>4,"code"=>440,"name"=>"MARGARITA"],
            ["state_id"=>4,"code"=>442,"name"=>"MARIA LA BAJA"],
            ["state_id"=>4,"code"=>458,"name"=>"MONTECRISTO"],
            ["state_id"=>4,"code"=>468,"name"=>"MOMPOS"],
            ["state_id"=>4,"code"=>473,"name"=>"MORALES"],
            ["state_id"=>4,"code"=>549,"name"=>"PINILLOS"],
            ["state_id"=>4,"code"=>580,"name"=>"REGIDOR"],
            ["state_id"=>4,"code"=>600,"name"=>"RIO VIEJO"],
            ["state_id"=>4,"code"=>620,"name"=>"SAN CRISTOBAL"],
            ["state_id"=>4,"code"=>647,"name"=>"SAN ESTANISLAO"],
            ["state_id"=>4,"code"=>650,"name"=>"SAN FERNANDO"],
            ["state_id"=>4,"code"=>654,"name"=>"SAN JACINTO"],
            ["state_id"=>4,"code"=>655,"name"=>"SAN JACINTO DEL CAUCA"],
            ["state_id"=>4,"code"=>657,"name"=>"SAN JUAN NEPOMUCENO"],
            ["state_id"=>4,"code"=>667,"name"=>"SAN MARTIN DE LOBA"],
            ["state_id"=>4,"code"=>670,"name"=>"SAN PABLO"],
            ["state_id"=>4,"code"=>673,"name"=>"SANTA CATALINA"],
            ["state_id"=>4,"code"=>683,"name"=>"SANTA ROSA"],
            ["state_id"=>4,"code"=>688,"name"=>"SANTA ROSA DEL SUR"],
            ["state_id"=>4,"code"=>744,"name"=>"SIMITI"],
            ["state_id"=>4,"code"=>760,"name"=>"SOPLAVIENTO"],
            ["state_id"=>4,"code"=>780,"name"=>"TALAIGUA NUEVO"],
            ["state_id"=>4,"code"=>810,"name"=>"TIQUISIO (PUERTO RICO)"],
            ["state_id"=>4,"code"=>836,"name"=>"TURBACO"],
            ["state_id"=>4,"code"=>838,"name"=>"TURBANA"],
            ["state_id"=>4,"code"=>873,"name"=>"VILLANUEVA"],
            ["state_id"=>4,"code"=>894,"name"=>"ZAMBRANO"],
            ["state_id"=>5,"code"=>1,"name"=>"TUNJA"],
            ["state_id"=>5,"code"=>22,"name"=>"ALMEIDA"],
            ["state_id"=>5,"code"=>47,"name"=>"AQUITANIA"],
            ["state_id"=>5,"code"=>51,"name"=>"ARCABUCO"],
            ["state_id"=>5,"code"=>87,"name"=>"BELEN"],
            ["state_id"=>5,"code"=>90,"name"=>"BERBEO"],
            ["state_id"=>5,"code"=>92,"name"=>"BETEITIVA"],
            ["state_id"=>5,"code"=>97,"name"=>"BOAVITA"],
            ["state_id"=>5,"code"=>104,"name"=>"BOYACA"],
            ["state_id"=>5,"code"=>106,"name"=>"BRICEÑO"],
            ["state_id"=>5,"code"=>109,"name"=>"BUENAVISTA"],
            ["state_id"=>5,"code"=>114,"name"=>"BUSBANZA"],
            ["state_id"=>5,"code"=>131,"name"=>"CALDAS"],
            ["state_id"=>5,"code"=>135,"name"=>"CAMPOHERMOSO"],
            ["state_id"=>5,"code"=>162,"name"=>"CERINZA"],
            ["state_id"=>5,"code"=>172,"name"=>"CHINAVITA"],
            ["state_id"=>5,"code"=>176,"name"=>"CHIQUINQUIRA"],
            ["state_id"=>5,"code"=>180,"name"=>"CHISCAS"],
            ["state_id"=>5,"code"=>183,"name"=>"CHITA"],
            ["state_id"=>5,"code"=>185,"name"=>"CHITARAQUE"],
            ["state_id"=>5,"code"=>187,"name"=>"CHIVATA"],
            ["state_id"=>5,"code"=>189,"name"=>"CIENEGA"],
            ["state_id"=>5,"code"=>204,"name"=>"COMBITA"],
            ["state_id"=>5,"code"=>212,"name"=>"COPER"],
            ["state_id"=>5,"code"=>215,"name"=>"CORRALES"],
            ["state_id"=>5,"code"=>218,"name"=>"COVARACHIA"],
            ["state_id"=>5,"code"=>223,"name"=>"CUBARA"],
            ["state_id"=>5,"code"=>224,"name"=>"CUCAITA"],
            ["state_id"=>5,"code"=>226,"name"=>"CUITIVA"],
            ["state_id"=>5,"code"=>232,"name"=>"CHIQUIZA"],
            ["state_id"=>5,"code"=>236,"name"=>"CHIVOR"],
            ["state_id"=>5,"code"=>238,"name"=>"DUITAMA"],
            ["state_id"=>5,"code"=>244,"name"=>"EL COCUY"],
            ["state_id"=>5,"code"=>248,"name"=>"EL ESPINO"],
            ["state_id"=>5,"code"=>272,"name"=>"FIRAVITOBA"],
            ["state_id"=>5,"code"=>276,"name"=>"FLORESTA"],
            ["state_id"=>5,"code"=>293,"name"=>"GACHANTIVA"],
            ["state_id"=>5,"code"=>296,"name"=>"GAMEZA"],
            ["state_id"=>5,"code"=>299,"name"=>"GARAGOA"],
            ["state_id"=>5,"code"=>317,"name"=>"GUACAMAYAS"],
            ["state_id"=>5,"code"=>322,"name"=>"GUATEQUE"],
            ["state_id"=>5,"code"=>325,"name"=>"GUAYATA"],
            ["state_id"=>5,"code"=>332,"name"=>"GUICAN"],
            ["state_id"=>5,"code"=>362,"name"=>"IZA"],
            ["state_id"=>5,"code"=>367,"name"=>"JENESANO"],
            ["state_id"=>5,"code"=>368,"name"=>"JERICO"],
            ["state_id"=>5,"code"=>377,"name"=>"LABRANZAGRANDE"],
            ["state_id"=>5,"code"=>380,"name"=>"LA CAPILLA"],
            ["state_id"=>5,"code"=>401,"name"=>"LA VICTORIA"],
            ["state_id"=>5,"code"=>403,"name"=>"LA UVITA"],
            ["state_id"=>5,"code"=>407,"name"=>"VILLA DE LEIVA"],
            ["state_id"=>5,"code"=>425,"name"=>"MACANAL"],
            ["state_id"=>5,"code"=>442,"name"=>"MARIPI"],
            ["state_id"=>5,"code"=>455,"name"=>"MIRAFLORES"],
            ["state_id"=>5,"code"=>464,"name"=>"MONGUA"],
            ["state_id"=>5,"code"=>466,"name"=>"MONGUI"],
            ["state_id"=>5,"code"=>469,"name"=>"MONIQUIRA"],
            ["state_id"=>5,"code"=>476,"name"=>"MOTAVITA"],
            ["state_id"=>5,"code"=>480,"name"=>"MUZO"],
            ["state_id"=>5,"code"=>491,"name"=>"NOBSA"],
            ["state_id"=>5,"code"=>494,"name"=>"NUEVO COLON"],
            ["state_id"=>5,"code"=>500,"name"=>"OICATA"],
            ["state_id"=>5,"code"=>507,"name"=>"OTANCHE"],
            ["state_id"=>5,"code"=>511,"name"=>"PACHAVITA"],
            ["state_id"=>5,"code"=>514,"name"=>"PAEZ"],
            ["state_id"=>5,"code"=>516,"name"=>"PAIPA"],
            ["state_id"=>5,"code"=>518,"name"=>"PAJARITO"],
            ["state_id"=>5,"code"=>522,"name"=>"PANQUEBA"],
            ["state_id"=>5,"code"=>531,"name"=>"PAUNA"],
            ["state_id"=>5,"code"=>533,"name"=>"PAYA"],
            ["state_id"=>5,"code"=>537,"name"=>"PAZ DEL RIO"],
            ["state_id"=>5,"code"=>542,"name"=>"PESCA"],
            ["state_id"=>5,"code"=>550,"name"=>"PISBA"],
            ["state_id"=>5,"code"=>572,"name"=>"PUERTO BOYACA"],
            ["state_id"=>5,"code"=>580,"name"=>"QUIPAMA"],
            ["state_id"=>5,"code"=>599,"name"=>"RAMIRIQUI"],
            ["state_id"=>5,"code"=>600,"name"=>"RAQUIRA"],
            ["state_id"=>5,"code"=>621,"name"=>"RONDON"],
            ["state_id"=>5,"code"=>632,"name"=>"SABOYA"],
            ["state_id"=>5,"code"=>638,"name"=>"SACHICA"],
            ["state_id"=>5,"code"=>646,"name"=>"SAMACA"],
            ["state_id"=>5,"code"=>660,"name"=>"SAN EDUARDO"],
            ["state_id"=>5,"code"=>664,"name"=>"SAN JOSE DE PARE"],
            ["state_id"=>5,"code"=>667,"name"=>"SAN LUIS DE GACENO"],
            ["state_id"=>5,"code"=>673,"name"=>"SAN MATEO"],
            ["state_id"=>5,"code"=>676,"name"=>"SAN MIGUEL DE SEMA"],
            ["state_id"=>5,"code"=>681,"name"=>"SAN PABLO DE BORBUR"],
            ["state_id"=>5,"code"=>686,"name"=>"SANTANA"],
            ["state_id"=>5,"code"=>690,"name"=>"SANTA MARIA"],
            ["state_id"=>5,"code"=>693,"name"=>"SANTA ROSA DE VITERBO"],
            ["state_id"=>5,"code"=>696,"name"=>"SANTA SOFIA"],
            ["state_id"=>5,"code"=>720,"name"=>"SATIVANORTE"],
            ["state_id"=>5,"code"=>723,"name"=>"SATIVASUR"],
            ["state_id"=>5,"code"=>740,"name"=>"SIACHOQUE"],
            ["state_id"=>5,"code"=>753,"name"=>"SOATA"],
            ["state_id"=>5,"code"=>755,"name"=>"SOCOTA"],
            ["state_id"=>5,"code"=>757,"name"=>"SOCHA"],
            ["state_id"=>5,"code"=>759,"name"=>"SOGAMOSO"],
            ["state_id"=>5,"code"=>761,"name"=>"SOMONDOCO"],
            ["state_id"=>5,"code"=>762,"name"=>"SORA"],
            ["state_id"=>5,"code"=>763,"name"=>"SOTAQUIRA"],
            ["state_id"=>5,"code"=>764,"name"=>"SORACA"],
            ["state_id"=>5,"code"=>774,"name"=>"SUSACON"],
            ["state_id"=>5,"code"=>776,"name"=>"SUTAMARCHAN"],
            ["state_id"=>5,"code"=>778,"name"=>"SUTATENZA"],
            ["state_id"=>5,"code"=>790,"name"=>"TASCO"],
            ["state_id"=>5,"code"=>798,"name"=>"TENZA"],
            ["state_id"=>5,"code"=>804,"name"=>"TIBANA"],
            ["state_id"=>5,"code"=>806,"name"=>"TIBASOSA"],
            ["state_id"=>5,"code"=>808,"name"=>"TINJACA"],
            ["state_id"=>5,"code"=>810,"name"=>"TIPACOQUE"],
            ["state_id"=>5,"code"=>814,"name"=>"TOCA"],
            ["state_id"=>5,"code"=>816,"name"=>"TOGUI"],
            ["state_id"=>5,"code"=>820,"name"=>"TOPAGA"],
            ["state_id"=>5,"code"=>822,"name"=>"TOTA"],
            ["state_id"=>5,"code"=>832,"name"=>"TUNUNGUA"],
            ["state_id"=>5,"code"=>835,"name"=>"TURMEQUE"],
            ["state_id"=>5,"code"=>837,"name"=>"TUTA"],
            ["state_id"=>5,"code"=>839,"name"=>"TUTASA"],
            ["state_id"=>5,"code"=>842,"name"=>"UMBITA"],
            ["state_id"=>5,"code"=>861,"name"=>"VENTAQUEMADA"],
            ["state_id"=>5,"code"=>879,"name"=>"VIRACACHA"],
            ["state_id"=>5,"code"=>897,"name"=>"ZETAQUIRA"],
            ["state_id"=>6,"code"=>1,"name"=>"MANIZALES"],
            ["state_id"=>6,"code"=>13,"name"=>"AGUADAS"],
            ["state_id"=>6,"code"=>42,"name"=>"ANSERMA"],
            ["state_id"=>6,"code"=>50,"name"=>"ARANZAZU"],
            ["state_id"=>6,"code"=>88,"name"=>"BELALCAZAR"],
            ["state_id"=>6,"code"=>174,"name"=>"CHINCHINA"],
            ["state_id"=>6,"code"=>272,"name"=>"FILADELFIA"],
            ["state_id"=>6,"code"=>380,"name"=>"LA DORADA"],
            ["state_id"=>6,"code"=>388,"name"=>"LA MERCED"],
            ["state_id"=>6,"code"=>433,"name"=>"MANZANARES"],
            ["state_id"=>6,"code"=>442,"name"=>"MARMATO"],
            ["state_id"=>6,"code"=>444,"name"=>"MARQUETALIA"],
            ["state_id"=>6,"code"=>446,"name"=>"MARULANDA"],
            ["state_id"=>6,"code"=>486,"name"=>"NEIRA"],
            ["state_id"=>6,"code"=>495,"name"=>"NORCASIA"],
            ["state_id"=>6,"code"=>513,"name"=>"PACORA"],
            ["state_id"=>6,"code"=>524,"name"=>"PALESTINA"],
            ["state_id"=>6,"code"=>541,"name"=>"PENSILVANIA"],
            ["state_id"=>6,"code"=>614,"name"=>"RIOSUCIO"],
            ["state_id"=>6,"code"=>616,"name"=>"RISARALDA"],
            ["state_id"=>6,"code"=>653,"name"=>"SALAMINA"],
            ["state_id"=>6,"code"=>662,"name"=>"SAMANA"],
            ["state_id"=>6,"code"=>665,"name"=>"SAN JOSE"],
            ["state_id"=>6,"code"=>777,"name"=>"SUPIA"],
            ["state_id"=>6,"code"=>867,"name"=>"VICTORIA"],
            ["state_id"=>6,"code"=>873,"name"=>"VILLAMARIA"],
            ["state_id"=>6,"code"=>877,"name"=>"VITERBO"],
            ["state_id"=>7,"code"=>1,"name"=>"FLORENCIA"],
            ["state_id"=>7,"code"=>29,"name"=>"ALBANIA"],
            ["state_id"=>7,"code"=>94,"name"=>"BELEN DE LOS ANDAQUIES"],
            ["state_id"=>7,"code"=>150,"name"=>"CARTAGENA DEL CHAIRA"],
            ["state_id"=>7,"code"=>205,"name"=>"CURILLO"],
            ["state_id"=>7,"code"=>247,"name"=>"EL DONCELLO"],
            ["state_id"=>7,"code"=>256,"name"=>"EL PAUJIL"],
            ["state_id"=>7,"code"=>410,"name"=>"LA MONTAÑITA"],
            ["state_id"=>7,"code"=>460,"name"=>"MILAN"],
            ["state_id"=>7,"code"=>479,"name"=>"MORELIA"],
            ["state_id"=>7,"code"=>592,"name"=>"PUERTO RICO"],
            ["state_id"=>7,"code"=>610,"name"=>"SAN JOSE DE FRAGUA"],
            ["state_id"=>7,"code"=>753,"name"=>"SAN VICENTE DEL CAGUAN"],
            ["state_id"=>7,"code"=>756,"name"=>"SOLANO"],
            ["state_id"=>7,"code"=>785,"name"=>"SOLITA"],
            ["state_id"=>7,"code"=>860,"name"=>"VALPARAISO"],
            ["state_id"=>8,"code"=>1,"name"=>"POPAYAN"],
            ["state_id"=>8,"code"=>22,"name"=>"ALMAGUER"],
            ["state_id"=>8,"code"=>50,"name"=>"ARGELIA"],
            ["state_id"=>8,"code"=>75,"name"=>"BALBOA"],
            ["state_id"=>8,"code"=>100,"name"=>"BOLIVAR"],
            ["state_id"=>8,"code"=>110,"name"=>"BUENOS AIRES"],
            ["state_id"=>8,"code"=>130,"name"=>"CAJIBIO"],
            ["state_id"=>8,"code"=>137,"name"=>"CALDONO"],
            ["state_id"=>8,"code"=>142,"name"=>"CALOTO"],
            ["state_id"=>8,"code"=>212,"name"=>"CORINTO"],
            ["state_id"=>8,"code"=>256,"name"=>"EL TAMBO"],
            ["state_id"=>8,"code"=>290,"name"=>"FLORENCIA"],
            ["state_id"=>8,"code"=>318,"name"=>"GUAPI"],
            ["state_id"=>8,"code"=>355,"name"=>"INZA"],
            ["state_id"=>8,"code"=>364,"name"=>"JAMBALO"],
            ["state_id"=>8,"code"=>392,"name"=>"LA SIERRA"],
            ["state_id"=>8,"code"=>397,"name"=>"LA VEGA"],
            ["state_id"=>8,"code"=>418,"name"=>"LOPEZ (MICAY)"],
            ["state_id"=>8,"code"=>450,"name"=>"MERCADERES"],
            ["state_id"=>8,"code"=>455,"name"=>"MIRANDA"],
            ["state_id"=>8,"code"=>473,"name"=>"MORALES"],
            ["state_id"=>8,"code"=>513,"name"=>"PADILLA"],
            ["state_id"=>8,"code"=>517,"name"=>"PAEZ (BELALCAZAR)"],
            ["state_id"=>8,"code"=>532,"name"=>"PATIA (EL BORDO)"],
            ["state_id"=>8,"code"=>533,"name"=>"PIAMONTE"],
            ["state_id"=>8,"code"=>548,"name"=>"PIENDAMO"],
            ["state_id"=>8,"code"=>573,"name"=>"PUERTO TEJADA"],
            ["state_id"=>8,"code"=>585,"name"=>"PURACE (COCONUCO)"],
            ["state_id"=>8,"code"=>622,"name"=>"ROSAS"],
            ["state_id"=>8,"code"=>693,"name"=>"SAN SEBASTIAN"],
            ["state_id"=>8,"code"=>698,"name"=>"SANTANDER DE QUILICHAO"],
            ["state_id"=>8,"code"=>701,"name"=>"SANTA ROSA"],
            ["state_id"=>8,"code"=>743,"name"=>"SILVIA"],
            ["state_id"=>8,"code"=>760,"name"=>"SOTARA (PAISPAMBA)"],
            ["state_id"=>8,"code"=>780,"name"=>"SUAREZ"],
            ["state_id"=>8,"code"=>807,"name"=>"TIMBIO"],
            ["state_id"=>8,"code"=>809,"name"=>"TIMBIQUI"],
            ["state_id"=>8,"code"=>821,"name"=>"TORIBIO"],
            ["state_id"=>8,"code"=>824,"name"=>"TOTORO"],
            ["state_id"=>8,"code"=>845,"name"=>"VILLARICA"],
            ["state_id"=>9,"code"=>1,"name"=>"VALLEDUPAR"],
            ["state_id"=>9,"code"=>11,"name"=>"AGUACHICA"],
            ["state_id"=>9,"code"=>13,"name"=>"AGUSTIN CODAZZI"],
            ["state_id"=>9,"code"=>32,"name"=>"ASTREA"],
            ["state_id"=>9,"code"=>45,"name"=>"BECERRIL"],
            ["state_id"=>9,"code"=>60,"name"=>"BOSCONIA"],
            ["state_id"=>9,"code"=>175,"name"=>"CHIMICHAGUA"],
            ["state_id"=>9,"code"=>178,"name"=>"CHIRIGUANA"],
            ["state_id"=>9,"code"=>228,"name"=>"CURUMANI"],
            ["state_id"=>9,"code"=>238,"name"=>"EL COPEY"],
            ["state_id"=>9,"code"=>250,"name"=>"EL PASO"],
            ["state_id"=>9,"code"=>295,"name"=>"GAMARRA"],
            ["state_id"=>9,"code"=>310,"name"=>"GONZALEZ"],
            ["state_id"=>9,"code"=>383,"name"=>"LA GLORIA"],
            ["state_id"=>9,"code"=>400,"name"=>"LA JAGUA IBIRICO"],
            ["state_id"=>9,"code"=>443,"name"=>"MANAURE (BALCON DEL CESAR)"],
            ["state_id"=>9,"code"=>517,"name"=>"PAILITAS"],
            ["state_id"=>9,"code"=>550,"name"=>"PELAYA"],
            ["state_id"=>9,"code"=>570,"name"=>"PUEBLO BELLO"],
            ["state_id"=>9,"code"=>614,"name"=>"RIO DE ORO"],
            ["state_id"=>9,"code"=>621,"name"=>"LA PAZ (ROBLES)"],
            ["state_id"=>9,"code"=>710,"name"=>"SAN ALBERTO"],
            ["state_id"=>9,"code"=>750,"name"=>"SAN DIEGO"],
            ["state_id"=>9,"code"=>770,"name"=>"SAN MARTIN"],
            ["state_id"=>9,"code"=>787,"name"=>"TAMALAMEQUE"],
            ["state_id"=>10,"code"=>1,"name"=>"MONTERIA"],
            ["state_id"=>10,"code"=>68,"name"=>"AYAPEL"],
            ["state_id"=>10,"code"=>79,"name"=>"BUENAVISTA"],
            ["state_id"=>10,"code"=>90,"name"=>"CANALETE"],
            ["state_id"=>10,"code"=>162,"name"=>"CERETE"],
            ["state_id"=>10,"code"=>168,"name"=>"CHIMA"],
            ["state_id"=>10,"code"=>182,"name"=>"CHINU"],
            ["state_id"=>10,"code"=>189,"name"=>"CIENAGA DE ORO"],
            ["state_id"=>10,"code"=>300,"name"=>"COTORRA"],
            ["state_id"=>10,"code"=>350,"name"=>"LA APARTADA"],
            ["state_id"=>10,"code"=>417,"name"=>"LORICA"],
            ["state_id"=>10,"code"=>419,"name"=>"LOS CORDOBAS"],
            ["state_id"=>10,"code"=>464,"name"=>"MOMIL"],
            ["state_id"=>10,"code"=>466,"name"=>"MONTELIBANO"],
            ["state_id"=>10,"code"=>500,"name"=>"MOÑITOS"],
            ["state_id"=>10,"code"=>555,"name"=>"PLANETA RICA"],
            ["state_id"=>10,"code"=>570,"name"=>"PUEBLO NUEVO"],
            ["state_id"=>10,"code"=>574,"name"=>"PUERTO ESCONDIDO"],
            ["state_id"=>10,"code"=>580,"name"=>"PUERTO LIBERTADOR"],
            ["state_id"=>10,"code"=>586,"name"=>"PURISIMA"],
            ["state_id"=>10,"code"=>660,"name"=>"SAHAGUN"],
            ["state_id"=>10,"code"=>670,"name"=>"SAN ANDRES SOTAVENTO"],
            ["state_id"=>10,"code"=>672,"name"=>"SAN ANTERO"],
            ["state_id"=>10,"code"=>675,"name"=>"SAN BERNARDO DEL VIENTO"],
            ["state_id"=>10,"code"=>678,"name"=>"SAN CARLOS"],
            ["state_id"=>10,"code"=>686,"name"=>"SAN PELAYO"],
            ["state_id"=>10,"code"=>807,"name"=>"TIERRALTA"],
            ["state_id"=>10,"code"=>855,"name"=>"VALENCIA"],
            ["state_id"=>11,"code"=>1,"name"=>"AGUA DE DIOS"],
            ["state_id"=>11,"code"=>19,"name"=>"ALBAN"],
            ["state_id"=>11,"code"=>35,"name"=>"ANAPOIMA"],
            ["state_id"=>11,"code"=>40,"name"=>"ANOLAIMA"],
            ["state_id"=>11,"code"=>53,"name"=>"ARBELAEZ"],
            ["state_id"=>11,"code"=>86,"name"=>"BELTRAN"],
            ["state_id"=>11,"code"=>95,"name"=>"BITUIMA"],
            ["state_id"=>11,"code"=>99,"name"=>"BOJACA"],
            ["state_id"=>11,"code"=>120,"name"=>"CABRERA"],
            ["state_id"=>11,"code"=>123,"name"=>"CACHIPAY"],
            ["state_id"=>11,"code"=>126,"name"=>"CAJICA"],
            ["state_id"=>11,"code"=>148,"name"=>"CAPARRAPI"],
            ["state_id"=>11,"code"=>151,"name"=>"CAQUEZA"],
            ["state_id"=>11,"code"=>154,"name"=>"CARMEN DE CARUPA"],
            ["state_id"=>11,"code"=>168,"name"=>"CHAGUANI"],
            ["state_id"=>11,"code"=>175,"name"=>"CHIA"],
            ["state_id"=>11,"code"=>178,"name"=>"CHIPAQUE"],
            ["state_id"=>11,"code"=>181,"name"=>"CHOACHI"],
            ["state_id"=>11,"code"=>183,"name"=>"CHOCONTA"],
            ["state_id"=>11,"code"=>200,"name"=>"COGUA"],
            ["state_id"=>11,"code"=>214,"name"=>"COTA"],
            ["state_id"=>11,"code"=>224,"name"=>"CUCUNUBA"],
            ["state_id"=>11,"code"=>245,"name"=>"EL COLEGIO"],
            ["state_id"=>11,"code"=>258,"name"=>"EL PEÑON"],
            ["state_id"=>11,"code"=>260,"name"=>"EL ROSAL"],
            ["state_id"=>11,"code"=>269,"name"=>"FACATATIVA"],
            ["state_id"=>11,"code"=>279,"name"=>"FOMEQUE"],
            ["state_id"=>11,"code"=>281,"name"=>"FOSCA"],
            ["state_id"=>11,"code"=>286,"name"=>"FUNZA"],
            ["state_id"=>11,"code"=>288,"name"=>"FUQUENE"],
            ["state_id"=>11,"code"=>290,"name"=>"FUSAGASUGA"],
            ["state_id"=>11,"code"=>293,"name"=>"GACHALA"],
            ["state_id"=>11,"code"=>295,"name"=>"GACHANCIPA"],
            ["state_id"=>11,"code"=>297,"name"=>"GACHETA"],
            ["state_id"=>11,"code"=>299,"name"=>"GAMA"],
            ["state_id"=>11,"code"=>307,"name"=>"GIRARDOT"],
            ["state_id"=>11,"code"=>312,"name"=>"GRANADA"],
            ["state_id"=>11,"code"=>317,"name"=>"GUACHETA"],
            ["state_id"=>11,"code"=>320,"name"=>"GUADUAS"],
            ["state_id"=>11,"code"=>322,"name"=>"GUASCA"],
            ["state_id"=>11,"code"=>324,"name"=>"GUATAQUI"],
            ["state_id"=>11,"code"=>326,"name"=>"GUATAVITA"],
            ["state_id"=>11,"code"=>328,"name"=>"GUAYABAL DE SIQUIMA"],
            ["state_id"=>11,"code"=>335,"name"=>"GUAYABETAL"],
            ["state_id"=>11,"code"=>339,"name"=>"GUTIERREZ"],
            ["state_id"=>11,"code"=>368,"name"=>"JERUSALEN"],
            ["state_id"=>11,"code"=>372,"name"=>"JUNIN"],
            ["state_id"=>11,"code"=>377,"name"=>"LA CALERA"],
            ["state_id"=>11,"code"=>386,"name"=>"LA MESA"],
            ["state_id"=>11,"code"=>394,"name"=>"LA PALMA"],
            ["state_id"=>11,"code"=>398,"name"=>"LA PEÑA"],
            ["state_id"=>11,"code"=>402,"name"=>"LA VEGA"],
            ["state_id"=>11,"code"=>407,"name"=>"LENGUAZAQUE"],
            ["state_id"=>11,"code"=>426,"name"=>"MACHETA"],
            ["state_id"=>11,"code"=>430,"name"=>"MADRID"],
            ["state_id"=>11,"code"=>436,"name"=>"MANTA"],
            ["state_id"=>11,"code"=>438,"name"=>"MEDINA"],
            ["state_id"=>11,"code"=>473,"name"=>"MOSQUERA"],
            ["state_id"=>11,"code"=>483,"name"=>"NARIÑO"],
            ["state_id"=>11,"code"=>486,"name"=>"NEMOCON"],
            ["state_id"=>11,"code"=>488,"name"=>"NILO"],
            ["state_id"=>11,"code"=>489,"name"=>"NIMAIMA"],
            ["state_id"=>11,"code"=>491,"name"=>"NOCAIMA"],
            ["state_id"=>11,"code"=>506,"name"=>"VENECIA (OSPINA PEREZ)"],
            ["state_id"=>11,"code"=>513,"name"=>"PACHO"],
            ["state_id"=>11,"code"=>518,"name"=>"PAIME"],
            ["state_id"=>11,"code"=>524,"name"=>"PANDI"],
            ["state_id"=>11,"code"=>530,"name"=>"PARATEBUENO"],
            ["state_id"=>11,"code"=>535,"name"=>"PASCA"],
            ["state_id"=>11,"code"=>572,"name"=>"PUERTO SALGAR"],
            ["state_id"=>11,"code"=>580,"name"=>"PULI"],
            ["state_id"=>11,"code"=>592,"name"=>"QUEBRADANEGRA"],
            ["state_id"=>11,"code"=>594,"name"=>"QUETAME"],
            ["state_id"=>11,"code"=>596,"name"=>"QUIPILE"],
            ["state_id"=>11,"code"=>599,"name"=>"APULO (RAFAEL REYES)"],
            ["state_id"=>11,"code"=>612,"name"=>"RICAURTE"],
            ["state_id"=>11,"code"=>645,"name"=>"SAN ANTONIO DEL TEQUENDAMA"],
            ["state_id"=>11,"code"=>649,"name"=>"SAN BERNARDO"],
            ["state_id"=>11,"code"=>653,"name"=>"SAN CAYETANO"],
            ["state_id"=>11,"code"=>658,"name"=>"SAN FRANCISCO"],
            ["state_id"=>11,"code"=>662,"name"=>"SAN JUAN DE RIOSECO"],
            ["state_id"=>11,"code"=>718,"name"=>"SASAIMA"],
            ["state_id"=>11,"code"=>736,"name"=>"SESQUILE"],
            ["state_id"=>11,"code"=>740,"name"=>"SIBATE"],
            ["state_id"=>11,"code"=>743,"name"=>"SILVANIA"],
            ["state_id"=>11,"code"=>745,"name"=>"SIMIJACA"],
            ["state_id"=>11,"code"=>754,"name"=>"SOACHA"],
            ["state_id"=>11,"code"=>758,"name"=>"SOPO"],
            ["state_id"=>11,"code"=>769,"name"=>"SUBACHOQUE"],
            ["state_id"=>11,"code"=>772,"name"=>"SUESCA"],
            ["state_id"=>11,"code"=>777,"name"=>"SUPATA"],
            ["state_id"=>11,"code"=>779,"name"=>"SUSA"],
            ["state_id"=>11,"code"=>781,"name"=>"SUTATAUSA"],
            ["state_id"=>11,"code"=>785,"name"=>"TABIO"],
            ["state_id"=>11,"code"=>793,"name"=>"TAUSA"],
            ["state_id"=>11,"code"=>797,"name"=>"TENA"],
            ["state_id"=>11,"code"=>799,"name"=>"TENJO"],
            ["state_id"=>11,"code"=>805,"name"=>"TIBACUY"],
            ["state_id"=>11,"code"=>807,"name"=>"TIBIRITA"],
            ["state_id"=>11,"code"=>815,"name"=>"TOCAIMA"],
            ["state_id"=>11,"code"=>817,"name"=>"TOCANCIPA"],
            ["state_id"=>11,"code"=>823,"name"=>"TOPAIPI"],
            ["state_id"=>11,"code"=>839,"name"=>"UBALA"],
            ["state_id"=>11,"code"=>841,"name"=>"UBAQUE"],
            ["state_id"=>11,"code"=>843,"name"=>"UBATE"],
            ["state_id"=>11,"code"=>845,"name"=>"UNE"],
            ["state_id"=>11,"code"=>851,"name"=>"UTICA"],
            ["state_id"=>11,"code"=>862,"name"=>"VERGARA"],
            ["state_id"=>11,"code"=>867,"name"=>"VIANI"],
            ["state_id"=>11,"code"=>871,"name"=>"VILLAGOMEZ"],
            ["state_id"=>11,"code"=>873,"name"=>"VILLAPINZON"],
            ["state_id"=>11,"code"=>875,"name"=>"VILLETA"],
            ["state_id"=>11,"code"=>878,"name"=>"VIOTA"],
            ["state_id"=>11,"code"=>885,"name"=>"YACOPI"],
            ["state_id"=>11,"code"=>898,"name"=>"ZIPACON"],
            ["state_id"=>11,"code"=>899,"name"=>"ZIPAQUIRA"],
            ["state_id"=>12,"code"=>1,"name"=>"QUIBDO (SAN FRANCISCO DE QUIBDO)"],
            ["state_id"=>12,"code"=>6,"name"=>"ACANDI"],
            ["state_id"=>12,"code"=>25,"name"=>"ALTO BAUDO (PIE DE PATO)"],
            ["state_id"=>12,"code"=>50,"name"=>"ATRATO"],
            ["state_id"=>12,"code"=>73,"name"=>"BAGADO"],
            ["state_id"=>12,"code"=>75,"name"=>"BAHIA SOLANO (MUTIS)"],
            ["state_id"=>12,"code"=>77,"name"=>"BAJO BAUDO (PIZARRO)"],
            ["state_id"=>12,"code"=>99,"name"=>"BOJAYA (BELLAVISTA)"],
            ["state_id"=>12,"code"=>135,"name"=>"CANTON DE SAN PABLO (MANAGRU)"],
            ["state_id"=>12,"code"=>205,"name"=>"CONDOTO"],
            ["state_id"=>12,"code"=>245,"name"=>"EL CARMEN DE ATRATO"],
            ["state_id"=>12,"code"=>250,"name"=>"LITORAL DEL BAJO SAN JUAN (SANTA GENOVEVA DE DOCORDO)"],
            ["state_id"=>12,"code"=>361,"name"=>"ISTMINA"],
            ["state_id"=>12,"code"=>372,"name"=>"JURADO"],
            ["state_id"=>12,"code"=>413,"name"=>"LLORO"],
            ["state_id"=>12,"code"=>425,"name"=>"MEDIO ATRATO"],
            ["state_id"=>12,"code"=>430,"name"=>"MEDIO BAUDO"],
            ["state_id"=>12,"code"=>491,"name"=>"NOVITA"],
            ["state_id"=>12,"code"=>495,"name"=>"NUQUI"],
            ["state_id"=>12,"code"=>600,"name"=>"RIOQUITO"],
            ["state_id"=>12,"code"=>615,"name"=>"RIOSUCIO"],
            ["state_id"=>12,"code"=>660,"name"=>"SAN JOSE DEL PALMAR"],
            ["state_id"=>12,"code"=>745,"name"=>"SIPI"],
            ["state_id"=>12,"code"=>787,"name"=>"TADO"],
            ["state_id"=>12,"code"=>800,"name"=>"UNGUIA"],
            ["state_id"=>12,"code"=>810,"name"=>"UNION PANAMERICANA"],
            ["state_id"=>13,"code"=>1,"name"=>"NEIVA"],
            ["state_id"=>13,"code"=>6,"name"=>"ACEVEDO"],
            ["state_id"=>13,"code"=>13,"name"=>"AGRADO"],
            ["state_id"=>13,"code"=>16,"name"=>"AIPE"],
            ["state_id"=>13,"code"=>20,"name"=>"ALGECIRAS"],
            ["state_id"=>13,"code"=>26,"name"=>"ALTAMIRA"],
            ["state_id"=>13,"code"=>78,"name"=>"BARAYA"],
            ["state_id"=>13,"code"=>132,"name"=>"CAMPOALEGRE"],
            ["state_id"=>13,"code"=>206,"name"=>"COLOMBIA"],
            ["state_id"=>13,"code"=>244,"name"=>"ELIAS"],
            ["state_id"=>13,"code"=>298,"name"=>"GARZON"],
            ["state_id"=>13,"code"=>306,"name"=>"GIGANTE"],
            ["state_id"=>13,"code"=>319,"name"=>"GUADALUPE"],
            ["state_id"=>13,"code"=>349,"name"=>"HOBO"],
            ["state_id"=>13,"code"=>357,"name"=>"IQUIRA"],
            ["state_id"=>13,"code"=>359,"name"=>"ISNOS (SAN JOSE DE ISNOS)"],
            ["state_id"=>13,"code"=>378,"name"=>"LA ARGENTINA"],
            ["state_id"=>13,"code"=>396,"name"=>"LA PLATA"],
            ["state_id"=>13,"code"=>483,"name"=>"NATAGA"],
            ["state_id"=>13,"code"=>503,"name"=>"OPORAPA"],
            ["state_id"=>13,"code"=>518,"name"=>"PAICOL"],
            ["state_id"=>13,"code"=>524,"name"=>"PALERMO"],
            ["state_id"=>13,"code"=>530,"name"=>"PALESTINA"],
            ["state_id"=>13,"code"=>548,"name"=>"PITAL"],
            ["state_id"=>13,"code"=>551,"name"=>"PITALITO"],
            ["state_id"=>13,"code"=>615,"name"=>"RIVERA"],
            ["state_id"=>13,"code"=>660,"name"=>"SALADOBLANCO"],
            ["state_id"=>13,"code"=>668,"name"=>"SAN AGUSTIN"],
            ["state_id"=>13,"code"=>676,"name"=>"SANTA MARIA"],
            ["state_id"=>13,"code"=>770,"name"=>"SUAZA"],
            ["state_id"=>13,"code"=>791,"name"=>"TARQUI"],
            ["state_id"=>13,"code"=>797,"name"=>"TESALIA"],
            ["state_id"=>13,"code"=>799,"name"=>"TELLO"],
            ["state_id"=>13,"code"=>801,"name"=>"TERUEL"],
            ["state_id"=>13,"code"=>807,"name"=>"TIMANA"],
            ["state_id"=>13,"code"=>872,"name"=>"VILLAVIEJA"],
            ["state_id"=>13,"code"=>885,"name"=>"YAGUARA"],
            ["state_id"=>14,"code"=>1,"name"=>"RIOHACHA"],
            ["state_id"=>14,"code"=>78,"name"=>"BARRANCAS"],
            ["state_id"=>14,"code"=>90,"name"=>"DIBULLA"],
            ["state_id"=>14,"code"=>98,"name"=>"DISTRACCION"],
            ["state_id"=>14,"code"=>110,"name"=>"EL MOLINO"],
            ["state_id"=>14,"code"=>279,"name"=>"FONSECA"],
            ["state_id"=>14,"code"=>378,"name"=>"HATONUEVO"],
            ["state_id"=>14,"code"=>420,"name"=>"LA JAGUA DEL PILAR"],
            ["state_id"=>14,"code"=>430,"name"=>"MAICAO"],
            ["state_id"=>14,"code"=>560,"name"=>"MANAURE"],
            ["state_id"=>14,"code"=>650,"name"=>"SAN JUAN DEL CESAR"],
            ["state_id"=>14,"code"=>847,"name"=>"URIBIA"],
            ["state_id"=>14,"code"=>855,"name"=>"URUMITA"],
            ["state_id"=>14,"code"=>874,"name"=>"VILLANUEVA"],
            ["state_id"=>15,"code"=>1,"name"=>"SANTA MARTA (DISTRITO TURISTICO CULTURAL E HISTORICO DE SANTA MARTA)"],
            ["state_id"=>15,"code"=>30,"name"=>"ALGARROBO"],
            ["state_id"=>15,"code"=>53,"name"=>"ARACATACA"],
            ["state_id"=>15,"code"=>58,"name"=>"ARIGUANI (EL DIFICIL)"],
            ["state_id"=>15,"code"=>161,"name"=>"CERRO SAN ANTONIO"],
            ["state_id"=>15,"code"=>170,"name"=>"CHIVOLO"],
            ["state_id"=>15,"code"=>189,"name"=>"CIENAGA"],
            ["state_id"=>15,"code"=>205,"name"=>"CONCORDIA"],
            ["state_id"=>15,"code"=>245,"name"=>"EL BANCO"],
            ["state_id"=>15,"code"=>258,"name"=>"EL PIÑON"],
            ["state_id"=>15,"code"=>268,"name"=>"EL RETEN"],
            ["state_id"=>15,"code"=>288,"name"=>"FUNDACION"],
            ["state_id"=>15,"code"=>318,"name"=>"GUAMAL"],
            ["state_id"=>15,"code"=>541,"name"=>"PEDRAZA"],
            ["state_id"=>15,"code"=>545,"name"=>"PIJIÑO DEL CARMEN (PIJIÑO)"],
            ["state_id"=>15,"code"=>551,"name"=>"PIVIJAY"],
            ["state_id"=>15,"code"=>555,"name"=>"PLATO"],
            ["state_id"=>15,"code"=>570,"name"=>"PUEBLOVIEJO"],
            ["state_id"=>15,"code"=>605,"name"=>"REMOLINO"],
            ["state_id"=>15,"code"=>660,"name"=>"SABANAS DE SAN ANGEL"],
            ["state_id"=>15,"code"=>675,"name"=>"SALAMINA"],
            ["state_id"=>15,"code"=>692,"name"=>"SAN SEBASTIAN DE BUENAVISTA"],
            ["state_id"=>15,"code"=>703,"name"=>"SAN ZENON"],
            ["state_id"=>15,"code"=>707,"name"=>"SANTA ANA"],
            ["state_id"=>15,"code"=>745,"name"=>"SITIONUEVO"],
            ["state_id"=>15,"code"=>798,"name"=>"TENERIFE"],
            ["state_id"=>16,"code"=>1,"name"=>"VILLAVICENCIO"],
            ["state_id"=>16,"code"=>6,"name"=>"ACACIAS"],
            ["state_id"=>16,"code"=>110,"name"=>"BARRANCA DE UPIA"],
            ["state_id"=>16,"code"=>124,"name"=>"CABUYARO"],
            ["state_id"=>16,"code"=>150,"name"=>"CASTILLA LA NUEVA"],
            ["state_id"=>16,"code"=>223,"name"=>"SAN LUIS DE CUBARRAL"],
            ["state_id"=>16,"code"=>226,"name"=>"CUMARAL"],
            ["state_id"=>16,"code"=>245,"name"=>"EL CALVARIO"],
            ["state_id"=>16,"code"=>251,"name"=>"EL CASTILLO"],
            ["state_id"=>16,"code"=>270,"name"=>"EL DORADO"],
            ["state_id"=>16,"code"=>287,"name"=>"FUENTE DE ORO"],
            ["state_id"=>16,"code"=>313,"name"=>"GRANADA"],
            ["state_id"=>16,"code"=>318,"name"=>"GUAMAL"],
            ["state_id"=>16,"code"=>325,"name"=>"MAPIRIPAN"],
            ["state_id"=>16,"code"=>330,"name"=>"MESETAS"],
            ["state_id"=>16,"code"=>350,"name"=>"LA MACARENA"],
            ["state_id"=>16,"code"=>370,"name"=>"LA URIBE"],
            ["state_id"=>16,"code"=>400,"name"=>"LEJANIAS"],
            ["state_id"=>16,"code"=>450,"name"=>"PUERTO CONCORDIA"],
            ["state_id"=>16,"code"=>568,"name"=>"PUERTO GAITAN"],
            ["state_id"=>16,"code"=>573,"name"=>"PUERTO LOPEZ"],
            ["state_id"=>16,"code"=>577,"name"=>"PUERTO LLERAS"],
            ["state_id"=>16,"code"=>590,"name"=>"PUERTO RICO"],
            ["state_id"=>16,"code"=>606,"name"=>"RESTREPO"],
            ["state_id"=>16,"code"=>680,"name"=>"SAN CARLOS DE GUAROA"],
            ["state_id"=>16,"code"=>683,"name"=>"SAN JUAN DE ARAMA"],
            ["state_id"=>16,"code"=>686,"name"=>"SAN JUANITO"],
            ["state_id"=>16,"code"=>689,"name"=>"SAN MARTIN"],
            ["state_id"=>16,"code"=>711,"name"=>"VISTAHERMOSA"],
            ["state_id"=>17,"code"=>1,"name"=>"PASTO (SAN JUAN DE PASTO)"],
            ["state_id"=>17,"code"=>19,"name"=>"ALBAN (SAN JOSE)"],
            ["state_id"=>17,"code"=>22,"name"=>"ALDANA"],
            ["state_id"=>17,"code"=>36,"name"=>"ANCUYA"],
            ["state_id"=>17,"code"=>51,"name"=>"ARBOLEDA (BERRUECOS)"],
            ["state_id"=>17,"code"=>79,"name"=>"BARBACOAS"],
            ["state_id"=>17,"code"=>83,"name"=>"BELEN"],
            ["state_id"=>17,"code"=>110,"name"=>"BUESACO"],
            ["state_id"=>17,"code"=>203,"name"=>"COLON (GENOVA)"],
            ["state_id"=>17,"code"=>207,"name"=>"CONSACA"],
            ["state_id"=>17,"code"=>210,"name"=>"CONTADERO"],
            ["state_id"=>17,"code"=>215,"name"=>"CORDOBA"],
            ["state_id"=>17,"code"=>224,"name"=>"CUASPUD (CARLOSAMA)"],
            ["state_id"=>17,"code"=>227,"name"=>"CUMBAL"],
            ["state_id"=>17,"code"=>233,"name"=>"CUMBITARA"],
            ["state_id"=>17,"code"=>240,"name"=>"CHACHAGUI"],
            ["state_id"=>17,"code"=>250,"name"=>"EL CHARCO"],
            ["state_id"=>17,"code"=>254,"name"=>"EL PEÑOL"],
            ["state_id"=>17,"code"=>256,"name"=>"EL ROSARIO"],
            ["state_id"=>17,"code"=>258,"name"=>"EL TABLON"],
            ["state_id"=>17,"code"=>260,"name"=>"EL TAMBO"],
            ["state_id"=>17,"code"=>287,"name"=>"FUNES"],
            ["state_id"=>17,"code"=>317,"name"=>"GUACHUCAL"],
            ["state_id"=>17,"code"=>320,"name"=>"GUAITARILLA"],
            ["state_id"=>17,"code"=>323,"name"=>"GUALMATAN"],
            ["state_id"=>17,"code"=>352,"name"=>"ILES"],
            ["state_id"=>17,"code"=>354,"name"=>"IMUES"],
            ["state_id"=>17,"code"=>356,"name"=>"IPIALES"],
            ["state_id"=>17,"code"=>378,"name"=>"LA CRUZ"],
            ["state_id"=>17,"code"=>381,"name"=>"LA FLORIDA"],
            ["state_id"=>17,"code"=>385,"name"=>"LA LLANADA"],
            ["state_id"=>17,"code"=>390,"name"=>"LA TOLA"],
            ["state_id"=>17,"code"=>399,"name"=>"LA UNION"],
            ["state_id"=>17,"code"=>405,"name"=>"LEIVA"],
            ["state_id"=>17,"code"=>411,"name"=>"LINARES"],
            ["state_id"=>17,"code"=>418,"name"=>"LOS ANDES (SOTOMAYOR)"],
            ["state_id"=>17,"code"=>427,"name"=>"MAGUI (PAYAN)"],
            ["state_id"=>17,"code"=>435,"name"=>"MALLAMA (PIEDRANCHA)"],
            ["state_id"=>17,"code"=>473,"name"=>"MOSQUERA"],
            ["state_id"=>17,"code"=>490,"name"=>"OLAYA HERRERA (BOCAS DE SATINGA)"],
            ["state_id"=>17,"code"=>506,"name"=>"OSPINA"],
            ["state_id"=>17,"code"=>520,"name"=>"FRANCISCO PIZARRO (SALAHONDA)"],
            ["state_id"=>17,"code"=>540,"name"=>"POLICARPA"],
            ["state_id"=>17,"code"=>560,"name"=>"POTOSI"],
            ["state_id"=>17,"code"=>565,"name"=>"PROVIDENCIA"],
            ["state_id"=>17,"code"=>573,"name"=>"PUERRES"],
            ["state_id"=>17,"code"=>585,"name"=>"PUPIALES"],
            ["state_id"=>17,"code"=>612,"name"=>"RICAURTE"],
            ["state_id"=>17,"code"=>621,"name"=>"ROBERTO PAYAN (SAN JOSE)"],
            ["state_id"=>17,"code"=>678,"name"=>"SAMANIEGO"],
            ["state_id"=>17,"code"=>683,"name"=>"SANDONA"],
            ["state_id"=>17,"code"=>685,"name"=>"SAN BERNARDO"],
            ["state_id"=>17,"code"=>687,"name"=>"SAN LORENZO"],
            ["state_id"=>17,"code"=>693,"name"=>"SAN PABLO"],
            ["state_id"=>17,"code"=>694,"name"=>"SAN PEDRO DE CARTAGO"],
            ["state_id"=>17,"code"=>696,"name"=>"SANTA BARBARA (ISCUANDE)"],
            ["state_id"=>17,"code"=>699,"name"=>"SANTA CRUZ (GUACHAVES)"],
            ["state_id"=>17,"code"=>720,"name"=>"SAPUYES"],
            ["state_id"=>17,"code"=>786,"name"=>"TAMINANGO"],
            ["state_id"=>17,"code"=>788,"name"=>"TANGUA"],
            ["state_id"=>17,"code"=>835,"name"=>"TUMACO"],
            ["state_id"=>17,"code"=>838,"name"=>"TUQUERRES"],
            ["state_id"=>17,"code"=>885,"name"=>"YACUANQUER"],
            ["state_id"=>18,"code"=>1,"name"=>"CUCUTA"],
            ["state_id"=>18,"code"=>3,"name"=>"ABREGO"],
            ["state_id"=>18,"code"=>51,"name"=>"ARBOLEDAS"],
            ["state_id"=>18,"code"=>99,"name"=>"BOCHALEMA"],
            ["state_id"=>18,"code"=>109,"name"=>"BUCARASICA"],
            ["state_id"=>18,"code"=>125,"name"=>"CACOTA"],
            ["state_id"=>18,"code"=>128,"name"=>"CACHIRA"],
            ["state_id"=>18,"code"=>172,"name"=>"CHINACOTA"],
            ["state_id"=>18,"code"=>174,"name"=>"CHITAGA"],
            ["state_id"=>18,"code"=>206,"name"=>"CONVENCION"],
            ["state_id"=>18,"code"=>223,"name"=>"CUCUTILLA"],
            ["state_id"=>18,"code"=>239,"name"=>"DURANIA"],
            ["state_id"=>18,"code"=>245,"name"=>"EL CARMEN"],
            ["state_id"=>18,"code"=>250,"name"=>"EL TARRA"],
            ["state_id"=>18,"code"=>261,"name"=>"EL ZULIA"],
            ["state_id"=>18,"code"=>313,"name"=>"GRAMALOTE"],
            ["state_id"=>18,"code"=>344,"name"=>"HACARI"],
            ["state_id"=>18,"code"=>347,"name"=>"HERRAN"],
            ["state_id"=>18,"code"=>377,"name"=>"LABATECA"],
            ["state_id"=>18,"code"=>385,"name"=>"LA ESPERANZA"],
            ["state_id"=>18,"code"=>398,"name"=>"LA PLAYA"],
            ["state_id"=>18,"code"=>405,"name"=>"LOS PATIOS"],
            ["state_id"=>18,"code"=>418,"name"=>"LOURDES"],
            ["state_id"=>18,"code"=>480,"name"=>"MUTISCUA"],
            ["state_id"=>18,"code"=>498,"name"=>"OCAÑA"],
            ["state_id"=>18,"code"=>518,"name"=>"PAMPLONA"],
            ["state_id"=>18,"code"=>520,"name"=>"PAMPLONITA"],
            ["state_id"=>18,"code"=>553,"name"=>"PUERTO SANTANDER"],
            ["state_id"=>18,"code"=>599,"name"=>"RAGONVALIA"],
            ["state_id"=>18,"code"=>660,"name"=>"SALAZAR"],
            ["state_id"=>18,"code"=>670,"name"=>"SAN CALIXTO"],
            ["state_id"=>18,"code"=>673,"name"=>"SAN CAYETANO"],
            ["state_id"=>18,"code"=>680,"name"=>"SANTIAGO"],
            ["state_id"=>18,"code"=>720,"name"=>"SARDINATA"],
            ["state_id"=>18,"code"=>743,"name"=>"SILOS"],
            ["state_id"=>18,"code"=>800,"name"=>"TEORAMA"],
            ["state_id"=>18,"code"=>810,"name"=>"TIBU"],
            ["state_id"=>18,"code"=>820,"name"=>"TOLEDO"],
            ["state_id"=>18,"code"=>871,"name"=>"VILLACARO"],
            ["state_id"=>18,"code"=>874,"name"=>"VILLA DEL ROSARIO"],
            ["state_id"=>19,"code"=>1,"name"=>"ARMENIA"],
            ["state_id"=>19,"code"=>111,"name"=>"BUENAVISTA"],
            ["state_id"=>19,"code"=>130,"name"=>"CALARCA"],
            ["state_id"=>19,"code"=>190,"name"=>"CIRCASIA"],
            ["state_id"=>19,"code"=>212,"name"=>"CORDOBA"],
            ["state_id"=>19,"code"=>272,"name"=>"FILANDIA"],
            ["state_id"=>19,"code"=>302,"name"=>"GENOVA"],
            ["state_id"=>19,"code"=>401,"name"=>"LA TEBAIDA"],
            ["state_id"=>19,"code"=>470,"name"=>"MONTENEGRO"],
            ["state_id"=>19,"code"=>548,"name"=>"PIJAO"],
            ["state_id"=>19,"code"=>594,"name"=>"QUIMBAYA"],
            ["state_id"=>19,"code"=>690,"name"=>"SALENTO"],
            ["state_id"=>20,"code"=>1,"name"=>"PEREIRA"],
            ["state_id"=>20,"code"=>45,"name"=>"APIA"],
            ["state_id"=>20,"code"=>75,"name"=>"BALBOA"],
            ["state_id"=>20,"code"=>88,"name"=>"BELEN DE UMBRIA"],
            ["state_id"=>20,"code"=>170,"name"=>"DOS QUEBRADAS"],
            ["state_id"=>20,"code"=>318,"name"=>"GUATICA"],
            ["state_id"=>20,"code"=>383,"name"=>"LA CELIA"],
            ["state_id"=>20,"code"=>400,"name"=>"LA VIRGINIA"],
            ["state_id"=>20,"code"=>440,"name"=>"MARSELLA"],
            ["state_id"=>20,"code"=>456,"name"=>"MISTRATO"],
            ["state_id"=>20,"code"=>572,"name"=>"PUEBLO RICO"],
            ["state_id"=>20,"code"=>594,"name"=>"QUINCHIA"],
            ["state_id"=>20,"code"=>682,"name"=>"SANTA ROSA DE CABAL"],
            ["state_id"=>20,"code"=>687,"name"=>"SANTUARIO"],
            ["state_id"=>21,"code"=>1,"name"=>"BUCARAMANGA"],
            ["state_id"=>21,"code"=>13,"name"=>"AGUADA"],
            ["state_id"=>21,"code"=>20,"name"=>"ALBANIA"],
            ["state_id"=>21,"code"=>51,"name"=>"ARATOCA"],
            ["state_id"=>21,"code"=>77,"name"=>"BARBOSA"],
            ["state_id"=>21,"code"=>79,"name"=>"BARICHARA"],
            ["state_id"=>21,"code"=>81,"name"=>"BARRANCABERMEJA"],
            ["state_id"=>21,"code"=>92,"name"=>"BETULIA"],
            ["state_id"=>21,"code"=>101,"name"=>"BOLIVAR"],
            ["state_id"=>21,"code"=>121,"name"=>"CABRERA"],
            ["state_id"=>21,"code"=>132,"name"=>"CALIFORNIA"],
            ["state_id"=>21,"code"=>147,"name"=>"CAPITANEJO"],
            ["state_id"=>21,"code"=>152,"name"=>"CARCASI"],
            ["state_id"=>21,"code"=>160,"name"=>"CEPITA"],
            ["state_id"=>21,"code"=>162,"name"=>"CERRITO"],
            ["state_id"=>21,"code"=>167,"name"=>"CHARALA"],
            ["state_id"=>21,"code"=>169,"name"=>"CHARTA"],
            ["state_id"=>21,"code"=>176,"name"=>"CHIMA"],
            ["state_id"=>21,"code"=>179,"name"=>"CHIPATA"],
            ["state_id"=>21,"code"=>190,"name"=>"CIMITARRA"],
            ["state_id"=>21,"code"=>207,"name"=>"CONCEPCION"],
            ["state_id"=>21,"code"=>209,"name"=>"CONFINES"],
            ["state_id"=>21,"code"=>211,"name"=>"CONTRATACION"],
            ["state_id"=>21,"code"=>217,"name"=>"COROMORO"],
            ["state_id"=>21,"code"=>229,"name"=>"CURITI"],
            ["state_id"=>21,"code"=>235,"name"=>"EL CARMEN DE CHUCURY"],
            ["state_id"=>21,"code"=>245,"name"=>"EL GUACAMAYO"],
            ["state_id"=>21,"code"=>250,"name"=>"EL PEÑON"],
            ["state_id"=>21,"code"=>255,"name"=>"EL PLAYON"],
            ["state_id"=>21,"code"=>264,"name"=>"ENCINO"],
            ["state_id"=>21,"code"=>266,"name"=>"ENCISO"],
            ["state_id"=>21,"code"=>271,"name"=>"FLORIAN"],
            ["state_id"=>21,"code"=>276,"name"=>"FLORIDABLANCA"],
            ["state_id"=>21,"code"=>296,"name"=>"GALAN"],
            ["state_id"=>21,"code"=>298,"name"=>"GAMBITA"],
            ["state_id"=>21,"code"=>307,"name"=>"GIRON"],
            ["state_id"=>21,"code"=>318,"name"=>"GUACA"],
            ["state_id"=>21,"code"=>320,"name"=>"GUADALUPE"],
            ["state_id"=>21,"code"=>322,"name"=>"GUAPOTA"],
            ["state_id"=>21,"code"=>324,"name"=>"GUAVATA"],
            ["state_id"=>21,"code"=>327,"name"=>"GUEPSA"],
            ["state_id"=>21,"code"=>344,"name"=>"HATO"],
            ["state_id"=>21,"code"=>368,"name"=>"JESUS MARIA"],
            ["state_id"=>21,"code"=>370,"name"=>"JORDAN"],
            ["state_id"=>21,"code"=>377,"name"=>"LA BELLEZA"],
            ["state_id"=>21,"code"=>385,"name"=>"LANDAZURI"],
            ["state_id"=>21,"code"=>397,"name"=>"LA PAZ"],
            ["state_id"=>21,"code"=>406,"name"=>"LEBRIJA"],
            ["state_id"=>21,"code"=>418,"name"=>"LOS SANTOS"],
            ["state_id"=>21,"code"=>425,"name"=>"MACARAVITA"],
            ["state_id"=>21,"code"=>432,"name"=>"MALAGA"],
            ["state_id"=>21,"code"=>444,"name"=>"MATANZA"],
            ["state_id"=>21,"code"=>464,"name"=>"MOGOTES"],
            ["state_id"=>21,"code"=>468,"name"=>"MOLAGAVITA"],
            ["state_id"=>21,"code"=>498,"name"=>"OCAMONTE"],
            ["state_id"=>21,"code"=>500,"name"=>"OIBA"],
            ["state_id"=>21,"code"=>502,"name"=>"ONZAGA"],
            ["state_id"=>21,"code"=>522,"name"=>"PALMAR"],
            ["state_id"=>21,"code"=>524,"name"=>"PALMAS DEL SOCORRO"],
            ["state_id"=>21,"code"=>533,"name"=>"PARAMO"],
            ["state_id"=>21,"code"=>547,"name"=>"PIEDECUESTA"],
            ["state_id"=>21,"code"=>549,"name"=>"PINCHOTE"],
            ["state_id"=>21,"code"=>572,"name"=>"PUENTE NACIONAL"],
            ["state_id"=>21,"code"=>573,"name"=>"PUERTO PARRA"],
            ["state_id"=>21,"code"=>575,"name"=>"PUERTO WILCHES"],
            ["state_id"=>21,"code"=>615,"name"=>"RIONEGRO"],
            ["state_id"=>21,"code"=>655,"name"=>"SABANA DE TORRES"],
            ["state_id"=>21,"code"=>669,"name"=>"SAN ANDRES"],
            ["state_id"=>21,"code"=>673,"name"=>"SAN BENITO"],
            ["state_id"=>21,"code"=>679,"name"=>"SAN GIL"],
            ["state_id"=>21,"code"=>682,"name"=>"SAN JOAQUIN"],
            ["state_id"=>21,"code"=>684,"name"=>"SAN JOSE DE MIRANDA"],
            ["state_id"=>21,"code"=>686,"name"=>"SAN MIGUEL"],
            ["state_id"=>21,"code"=>689,"name"=>"SAN VICENTE DE CHUCURI"],
            ["state_id"=>21,"code"=>705,"name"=>"SANTA BARBARA"],
            ["state_id"=>21,"code"=>720,"name"=>"SANTA HELENA DEL OPON"],
            ["state_id"=>21,"code"=>745,"name"=>"SIMACOTA"],
            ["state_id"=>21,"code"=>755,"name"=>"SOCORRO"],
            ["state_id"=>21,"code"=>770,"name"=>"SUAITA"],
            ["state_id"=>21,"code"=>773,"name"=>"SUCRE"],
            ["state_id"=>21,"code"=>780,"name"=>"SURATA"],
            ["state_id"=>21,"code"=>820,"name"=>"TONA"],
            ["state_id"=>21,"code"=>855,"name"=>"VALLE SAN JOSE"],
            ["state_id"=>21,"code"=>861,"name"=>"VELEZ"],
            ["state_id"=>21,"code"=>867,"name"=>"VETAS"],
            ["state_id"=>21,"code"=>872,"name"=>"VILLANUEVA"],
            ["state_id"=>21,"code"=>895,"name"=>"ZAPATOCA"],
            ["state_id"=>22,"code"=>1,"name"=>"SINCELEJO"],
            ["state_id"=>22,"code"=>110,"name"=>"BUENAVISTA"],
            ["state_id"=>22,"code"=>124,"name"=>"CAIMITO"],
            ["state_id"=>22,"code"=>204,"name"=>"COLOSO (RICAURTE)"],
            ["state_id"=>22,"code"=>215,"name"=>"COROZAL"],
            ["state_id"=>22,"code"=>230,"name"=>"CHALAN"],
            ["state_id"=>22,"code"=>235,"name"=>"GALERAS (NUEVA GRANADA)"],
            ["state_id"=>22,"code"=>265,"name"=>"GUARANDA"],
            ["state_id"=>22,"code"=>400,"name"=>"LA UNION"],
            ["state_id"=>22,"code"=>418,"name"=>"LOS PALMITOS"],
            ["state_id"=>22,"code"=>429,"name"=>"MAJAGUAL"],
            ["state_id"=>22,"code"=>473,"name"=>"MORROA"],
            ["state_id"=>22,"code"=>508,"name"=>"OVEJAS"],
            ["state_id"=>22,"code"=>523,"name"=>"PALMITO"],
            ["state_id"=>22,"code"=>670,"name"=>"SAMPUES"],
            ["state_id"=>22,"code"=>678,"name"=>"SAN BENITO ABAD"],
            ["state_id"=>22,"code"=>702,"name"=>"SAN JUAN DE BETULIA"],
            ["state_id"=>22,"code"=>708,"name"=>"SAN MARCOS"],
            ["state_id"=>22,"code"=>713,"name"=>"SAN ONOFRE"],
            ["state_id"=>22,"code"=>717,"name"=>"SAN PEDRO"],
            ["state_id"=>22,"code"=>742,"name"=>"SINCE"],
            ["state_id"=>22,"code"=>771,"name"=>"SUCRE"],
            ["state_id"=>22,"code"=>820,"name"=>"TOLU"],
            ["state_id"=>22,"code"=>823,"name"=>"TOLUVIEJO"],
            ["state_id"=>23,"code"=>1,"name"=>"IBAGUE"],
            ["state_id"=>23,"code"=>24,"name"=>"ALPUJARRA"],
            ["state_id"=>23,"code"=>26,"name"=>"ALVARADO"],
            ["state_id"=>23,"code"=>30,"name"=>"AMBALEMA"],
            ["state_id"=>23,"code"=>43,"name"=>"ANZOATEGUI"],
            ["state_id"=>23,"code"=>55,"name"=>"ARMERO (GUAYABAL)"],
            ["state_id"=>23,"code"=>67,"name"=>"ATACO"],
            ["state_id"=>23,"code"=>124,"name"=>"CAJAMARCA"],
            ["state_id"=>23,"code"=>148,"name"=>"CARMEN APICALA"],
            ["state_id"=>23,"code"=>152,"name"=>"CASABIANCA"],
            ["state_id"=>23,"code"=>168,"name"=>"CHAPARRAL"],
            ["state_id"=>23,"code"=>200,"name"=>"COELLO"],
            ["state_id"=>23,"code"=>217,"name"=>"COYAIMA"],
            ["state_id"=>23,"code"=>226,"name"=>"CUNDAY"],
            ["state_id"=>23,"code"=>236,"name"=>"DOLORES"],
            ["state_id"=>23,"code"=>268,"name"=>"ESPINAL"],
            ["state_id"=>23,"code"=>270,"name"=>"FALAN"],
            ["state_id"=>23,"code"=>275,"name"=>"FLANDES"],
            ["state_id"=>23,"code"=>283,"name"=>"FRESNO"],
            ["state_id"=>23,"code"=>319,"name"=>"GUAMO"],
            ["state_id"=>23,"code"=>347,"name"=>"HERVEO"],
            ["state_id"=>23,"code"=>349,"name"=>"HONDA"],
            ["state_id"=>23,"code"=>352,"name"=>"ICONONZO"],
            ["state_id"=>23,"code"=>408,"name"=>"LERIDA"],
            ["state_id"=>23,"code"=>411,"name"=>"LIBANO"],
            ["state_id"=>23,"code"=>443,"name"=>"MARIQUITA"],
            ["state_id"=>23,"code"=>449,"name"=>"MELGAR"],
            ["state_id"=>23,"code"=>461,"name"=>"MURILLO"],
            ["state_id"=>23,"code"=>483,"name"=>"NATAGAIMA"],
            ["state_id"=>23,"code"=>504,"name"=>"ORTEGA"],
            ["state_id"=>23,"code"=>520,"name"=>"PALOCABILDO"],
            ["state_id"=>23,"code"=>547,"name"=>"PIEDRAS"],
            ["state_id"=>23,"code"=>555,"name"=>"PLANADAS"],
            ["state_id"=>23,"code"=>563,"name"=>"PRADO"],
            ["state_id"=>23,"code"=>585,"name"=>"PURIFICACION"],
            ["state_id"=>23,"code"=>616,"name"=>"RIOBLANCO"],
            ["state_id"=>23,"code"=>622,"name"=>"RONCESVALLES"],
            ["state_id"=>23,"code"=>624,"name"=>"ROVIRA"],
            ["state_id"=>23,"code"=>671,"name"=>"SALDAÑA"],

        ]);
        //
    }
}
